version: '3'

services:
  dbmanager:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./dbmanager:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    volumes:
      - ./db-server/db:/var/lib/mysql
      - ./db-server/DB_DUMP:/var/www/DB
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "33075:3306"